services:
  auth:
    build:
      context: .
      dockerfile: docker/Dockerfile.auth
    environment:
      - EXAMPLE_VAR=5
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    networks:
      - messenger-network
    depends_on:
      - postgres

  user:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    environment:
      - EXAMPLE_VAR=5
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    networks:
      - messenger-network
    depends_on:
      - postgres
  
  message:
    build:
      context: .
      dockerfile: docker/Dockerfile.message
    environment:
      - EXAMPLE_VAR=5
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    networks:
      - messenger-network
    depends_on:
      - postgres

  caddy:
    image: caddy:latest
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - messenger-network
    depends_on:
      - auth
      - user

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - messenger-network

networks:
  messenger-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
