services:
  auth:
    build:
      context: .
      dockerfile: docker/Dockerfile.auth
    environment:
      - OTEL_SERVICE_NAME=auth
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4318
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - messenger-network
    depends_on:
      - postgres

  user:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    environment:
      - OTEL_SERVICE_NAME=user
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4318
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - messenger-network
    depends_on:
      - postgres
  
  message:
    build:
      context: .
      dockerfile: docker/Dockerfile.message
    environment:
      - OTEL_SERVICE_NAME=message
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4318
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - messenger-network
    depends_on:
      - postgres

  caddy:
    image: caddy:latest
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - messenger-network
    depends_on:
      - auth
      - user

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init-db.sql.template:/docker-entrypoint-initdb.d/init-db.sql.template
    networks:
      - messenger-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "14269:14269"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    volumes:
      - jaeger_data:/data
    networks:
      - messenger-network

networks:
  messenger-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  jaeger_data:
    driver: local