services:
  auth:
    build:
      context: .
      dockerfile: docker/Dockerfile.auth
    environment:
      - EXAMPLE_VAR=5
    networks:
      - messenger-network

  user:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    environment:
      - EXAMPLE_VAR=5
    networks:
      - messenger-network

  caddy:
    image: caddy:latest
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - messenger-network
    depends_on:
      - auth
      - user

networks:
  messenger-network:
    driver: bridge